name: Deploy to dev environment.

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'functions/**'
      - 'website/**'

jobs:
  confirm_pre_conditions:
    name: Confirm pre-conditons for continue build&deploy job.
    runs-on: ubuntu-latest
    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    outputs:
      skip_ci: ${{ steps.confirmEnvValues.outputs.value }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Get setting for continue this workflow
        id: lookupDeployOnCommitDevelop
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.setup.deployOnCommitDevelop' 'config.yaml'
      - name: Confirm environment values
        id: confirmEnvValues
        run: |
          if [ -z $GCLOUD_SERVICE_KEY ]; then
            echo "GCLOUD_SERVICE_KEY is not set"
            echo "value=true" >> $GITHUB_OUTPUT
          elif [ '${{steps.lookupDeployOnCommitDevelop.outputs.result }}' != 'true' ]; then
            echo "deployOnCommitDevelop was set false"
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi
  build_and_deploy:
    name: Call hugo and deploy to firebase.
    needs: confirm_pre_conditions
    if: ${{ needs.confirm_pre_conditions.outputs.skip_ci != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "${{ needs.confirm_pre_conditions.outputs.skip_ci }}"
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      # GOOGLE_APPLICATION_CREDENTIALS is now set by the above action
      - name: Get Hugo Version from config
        id: lookupHugoVersion
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.setup.hugoVersion' 'config.yaml'
      - name: Get firebase project id from config
        id: lookupFirebaseProjectId
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.firebase.generatedProjectId' 'config.yaml'
      - name: Get Node Version from config
        id: lookupNodeVersion
        uses: mikefarah/yq@v4
        with:
          cmd: yq '.setup.nodeVersion' 'config.yaml'
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.lookupNodeVersion.outputs.result }}
          cache: npm
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.lookupHugoVersion.outputs.result }}
          extended: true
      - name: Install Dependencies
        run: |
          npm install -g firebase-tools
          npm ci
      - name: Build and deploy
        run: |
          # Only run deployment steps if on the develop branch
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            firebase use ${{ steps.lookupFirebaseProjectId.outputs.result }}
            firebase target:apply hosting dev dev-${{ steps.lookupFirebaseProjectId.outputs.result }}
            npm run deploy:dev
          else
            echo "Skipping deployment steps on non-develop branch (${{ github.ref_name }})."
            # Optionally run build steps without deploy for testing
            (cd website && hugo) # Assuming non-minified build for dev
            # npm run build:functions # If you have a build script for functions
          fi