name: Deploy to dev environment.

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'functions/**'
      - 'website/**'

jobs:
  confirm_pre_conditions:
    name: Confirm pre-conditons for continue build&deploy job.
    runs-on: ubuntu-latest
    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    outputs:
      skip_ci: ${{ steps.confirmEnvValues.outputs.value }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Get setting for continue this workflow
        id: lookupDeployOnCommitDevelop
        uses: mikefarah/yq@master
        with:
          cmd: yq '.setup.deployOnCommitDevelop' 'config.yaml'
      - name: Confirm environment values
        id: confirmEnvValues
        run: |
          if [ -z $GCLOUD_SERVICE_KEY ]; then
            echo "GCLOUD_SERVICE_KEY is not set"
            echo "value=true" >> $GITHUB_OUTPUT
          elif [ '${{steps.lookupDeployOnCommitDevelop.outputs.result }}' != 'true' ]; then
            echo "deployOnCommitDevelop was set false"
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi
  build_and_deploy:
    name: Call hugo and deploy to firebase.
    needs: confirm_pre_conditions
    if: ${{ needs.confirm_pre_conditions.outputs.skip_ci != 'true' }}
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    steps:
      - name: debug
        run: |
          echo "${{ needs.confirm_pre_conditions.outputs.skip_ci }}"
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Get Hugo Version from config
        id: lookupHugoVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq '.setup.hugoVersion' 'config.yaml'
      - name: Get firebase project id from config
        id: lookupFirebaseProjectId
        uses: mikefarah/yq@master
        with:
          cmd: yq '.firebase.projectId' 'config.yaml'
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.lookupHugoVersion.outputs.result }}
          extended: true
      - name: make GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - name: Install Dependencies
        run: |
          npm install -g firebase-tools
          npm ci
      - name: Build and deploy
        run: |
          firebase use ${{ steps.lookupFirebaseProjectId.outputs.result }}
          firebase target:apply hosting dev dev-${{ steps.lookupFirebaseProjectId.outputs.result }}
          npm run deploy:dev
